<?php
/**
 * BodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HelloAsso\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hello Asso
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace HelloAsso\Api;

/**
 * BodyTest Class Doc Comment
 *
 * @category    Class
 * @description Body
 * @package     HelloAsso\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Body"
     */
    public function testBody()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "client_secret"
     */
    public function testPropertyClientSecret()
    {
    }

    /**
     * Test attribute "grant_type"
     */
    public function testPropertyGrantType()
    {
    }

    /**
     * Test attribute "refresh_token"
     */
    public function testPropertyRefreshToken()
    {
    }

    /**
     * Test attribute "user_email"
     */
    public function testPropertyUserEmail()
    {
    }

    /**
     * Test attribute "user_first_name"
     */
    public function testPropertyUserFirstName()
    {
    }

    /**
     * Test attribute "user_last_name"
     */
    public function testPropertyUserLastName()
    {
    }

    /**
     * Test attribute "organization_name"
     */
    public function testPropertyOrganizationName()
    {
    }

    /**
     * Test attribute "organization_address"
     */
    public function testPropertyOrganizationAddress()
    {
    }

    /**
     * Test attribute "organization_zipcode"
     */
    public function testPropertyOrganizationZipcode()
    {
    }

    /**
     * Test attribute "organization_city"
     */
    public function testPropertyOrganizationCity()
    {
    }

    /**
     * Test attribute "organization_phone"
     */
    public function testPropertyOrganizationPhone()
    {
    }

    /**
     * Test attribute "organization_type"
     */
    public function testPropertyOrganizationType()
    {
    }

    /**
     * Test attribute "organization_website"
     */
    public function testPropertyOrganizationWebsite()
    {
    }
}
