<?php
/**
 * OrganizationCampaignsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  HelloAsso\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hello Asso
 *
 * www.helloasso.com Api specifications
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace HelloAsso\Api;

/**
 * OrganizationCampaignsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description OrganizationCampaignsResponse
 * @package     HelloAsso\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrganizationCampaignsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrganizationCampaignsResponse"
     */
    public function testOrganizationCampaignsResponse()
    {
    }

    /**
     * Test attribute "resources"
     */
    public function testPropertyResources()
    {
    }

    /**
     * Test attribute "pagination"
     */
    public function testPropertyPagination()
    {
    }
}
